apiVersion: v1 
kind: Service 
metadata:
  name: falsk-app-service
  namespace: flask-ns  
  labels:
    app: flask-app
    tier: frontend    
spec:
  selector: 
    app: flask-app
    tier: frontend    
  type: NodePort
  ports:
    - targetPort: 5000
      port: 80
      protocol: TCP
      nodePort: 30007
    
