apiVersion: v1 
kind: Service
metadata:
  name: mongo-svc
  namespace: flask-ns  
  labels:
    app: flask-app
    tier: backend
spec:
  selector:
    app: flask-app
    tier: backend
  ports:
    - targetPort: 27017
      port: 27017