apiVersion: v1 
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: flask-ns  
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
   storage: 30Gi
  hostPath:
    path: /tmp/data
  volumeMode: Filesystem