apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mongo-deploy
  namespace: flask-ns  
  labels:
    app: flask-app
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
      tier: backend
  template:
    metadata:
      name: mongo-pod
      labels:
        app: flask-app
        tier: backend
    spec:
      containers:
        - name: mongo-container
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data
              name: data-vol
      volumes:
        - name: data-vol
          persistentVolumeClaim:
             claimName: mongo-pvc